language: php

php:
    - 5.3
    - 5.4
    - 5.5

before_script:
    - curl http://getcomposer.org/installer | php
    - php composer.phar require satooshi/php-coveralls:dev-master brianium/paratest:dev-master --dev --prefer-source

script:
    - mkdir -p build/logs
    - ./vendor/bin/paratest --coverage-clover build/logs/clover.xml

after_script:
    - php vendor/bin/coveralls -v